### ISSUE TITLE
Attributions Missing

### ISSUE THREAD

**Issue by ApproachingApathy** [SMinTexas/houston-landing#20]
Remember to add attributions!

`<div>Icons made by <a href="https://www.flaticon.com/authors/bqlqn" title="bqlqn">bqlqn</a> from <a href="https://www.flaticon.com/"     title="Flaticon">www.flaticon.com</a></div>`

You are required to display the message “ [Powered by Dark Sky](https://darksky.net/poweredby/) ” that links to https://darksky.net/poweredby/ somewhere prominent in your app or service. If attribution isn’t for you, email  [sales@darksky.net](mailto:sales@darksky.net)  for details about white labeling.

**Comment by SMinTexas** [comment]
Handled this issue with the creation of the credits.html page.  It is reached via a link located in the footer on the About page.
